### ISSUE TITLE
Error 401 / WARNING:root:Got recoverable error from GET

### ISSUE THREAD

**Issue by mbuyukkarakas** [OSidorenkov/zabbix-jira#11]
Hello all,
In our environment, we use Zabbix 4.0.1 / CentOS7
We would like to reach Jira Cloud and open/close tickets. I applied the steps but I'm receiving this error.

WARNING:root:Got recoverable error from GET https://xxxxxx.atlassian.net/rest/api/2/serverInfo, will retry [1/3] in 0.96207812462s. Err: 401

Then I created a API Token by following Jira documentation. Then I changed the config.py as below.

jira_server = 'https://xxxxxxxx.atlassian.net'
jira_user = 'zabbix@xxxxxxx.com:TOKEN_ID'
jira_pass = 'Password'

Then I used the command to create test ticket.

python jirabix.py "zabbix@xxxxxxx.com:TOKEN_ID" "ZBX TEST" "Mesaj govdesi"

Still I'm receiving the same error message.

Could you help me please ?
Best regards.

**Comment by OSidorenkov** [comment]
I didn't test cloud Jira, sorry 😐. Only server version.

**Comment by gargmukul95** [comment]
Hey,

Try with following changes in config.py. It will work-
jira_server = 'https://xxxxxxxx.atlassian.net'
jira_user = 'zabbix@xxxxxxx.com'
jira_pass = 'TOKEN_ID'
