### ISSUE TITLE
Issue not transitioned to Done

### ISSUE THREAD

**Issue by ghost** [OSidorenkov/zabbix-jira#3]
When Zabbix fires an recovery alert, the Jira issue is not transitioned to Done. I adjusted the transition ID so it should be okay.

**Comment by OSidorenkov** [comment]
Hello, Christiaan! You are right. First, you need to get ID of "Done" status. It's may be unique on different Jira apps. So I left a little instruction on how to find the right ID in the _config.py.example_:
jira_close_status = '41'  # unique status for project. Read https://jira.readthedocs.io/en/master/examples.html#transitions to get your id

Thx for using this module =)
