### ISSUE TITLE
graph is not going to jira and transition state is not changeing to done

### ISSUE THREAD

**Issue by ashokv54** [OSidorenkov/zabbix-jira#6]
Hi 

graph attachment is not working of zabbix, and transition state is not changing to done in jira 

JIRA version v7.11.1
zabbix version v3.0.20

thanks in advance

**Comment by OSidorenkov** [comment]
@ashokv54 Can you show me your transition state in Jira and jira_transition from config.py.
Also show your actions in zabbix

**Comment by ashokv54** [comment]
zabbix action and config.py  
![zabbix-2](https://user-images.githubusercontent.com/29498166/44023222-7696dd02-9f07-11e8-8808-f8e9cfde856e.JPG)
![zabbix-1](https://user-images.githubusercontent.com/29498166/44023224-76cb4448-9f07-11e8-90aa-ea324f135d82.JPG)
![zabbix-3](https://user-images.githubusercontent.com/29498166/44023225-76fab52a-9f07-11e8-9117-9c1b1462c1e0.JPG)


if i sending the same action code  by entry.txt its working fine for attachment and task closing.

**Comment by OSidorenkov** [comment]
Please, check this issue https://github.com/OSidorenkov/zabbix-jira/issues/8.
Maybe database file has not been created or zabbix user haven't access to it.
